# 1. On part de Python officiel
FROM python:3.9-slim

# 2. On installe les outils SYSTÈME communs à TOUS (FFmpeg, GL libs pour YOLO)
# Cela ne sera fait qu'une seule fois ici !
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 3. On installe les librairies Python communes (Optionnel, mais pratique)
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Spécifique au Downscaler
COPY main.py .
CMD ["python", "-u", "main.py"]