# On repart de l'image downscaler qui contient déjà TOUTES les libs du common
FROM vidp-base:latest

WORKDIR /app

# On n'a besoin de rien installer, tout est déjà là.
# On copie juste le code spécifique à ce service.
COPY requirements.txt .
COPY main.py .

# On recrée les dossiers par sécurité (même s'ils existent déjà dans l'image parente)
RUN mkdir -p /mnt/data/input /mnt/data/processed

CMD ["python", "main.py"]